### ISSUE TITLE
Showing all detected rectangles only once after the completion.

### ISSUE THREAD

**Issue by Griffintaur** [Griffintaur/Padestrian-Detection#1]
currently, it shows while the algorithm is running one on one basis but it would be better if all detected pedestrians are shown at once after the also stopped working.

**Comment by ghost** [comment]
Weirdly I cant find the package cv2. Tried to pip install it and it didnt work

**Comment by Griffintaur** [comment]
are you using anaconda for python then use conda command for installing opencv

**Comment by Ant0nyJM** [comment]
#### it shows attribute error on running Main.py
_antonyjm@ajmfedora Padestrian-Detection-master]$ python Main.py
/home/antonyjm/Desktop/Padestrian-Detection-master/Padestrian-Detection-master/Output/
/home/antonyjm/Desktop/Padestrian-Detection-master/Padestrian-Detection-master/Input/pos/person_327a.png
libpng error: IDAT: invalid distance too far back
/home/antonyjm/Desktop/Padestrian-Detection-master/Padestrian-Detection-master/Input/pos/person_327a.png
Traceback (most recent call last):
  File "Main.py", line 107, in <module>
    App()
  File "Main.py", line 42, in App
    obj=Imagehandler(paths[i])
  File "/home/antonyjm/Desktop/Padestrian-Detection-master/Padestrian-Detection-master/ImageHandler.py", line 23, in __init__
    print self.Image.shape[:2]
AttributeError: 'NoneType' object has no attribute 'shape'_

**Comment by utkarshagarwal1312** [comment]
Is the issue assigned or is its still open for development and PR ?

**Comment by akshaydmc** [comment]
Can I do it?

**Comment by Griffintaur** [comment]
@AkkiBond sure.

**Comment by shubhampkj** [comment]
Hi @Griffintaur 
Is it still up for grabs?
I would love to work on it during Hacktoberfest

**Comment by raj-chinagundi** [comment]
Hey is this issue still active ,can i work on it?

**Comment by sara184** [comment]
Hey, can I work on this? @Griffintaur

**Comment by whoisvishesh** [comment]
Hey, @Griffintaur is the issue still active? Can I work on this?

**Comment by AthJoshi** [comment]
Hey, @Griffintaur  is the issue still open and up for grabs? would love to contribute during hacktober.

**Comment by ashrinc** [comment]
hey ,@Griffintaur is it still up for grabs?

**Comment by Griffintaur** [comment]
yes

**Comment by ashrinc** [comment]
Thanks for confirming! I’d love to work on this issue.
I’ll start investigating and update you if I have questions or progress.

**Comment by ashrinc** [comment]
I’d really appreciate it if you could take a look at my PR when you have time.
Please let me know if any changes are needed.

**Comment by raj-chinagundi** [comment]
@Griffintaur you took 5 years to respond, thats half a decade
